import "@/styles/globals.css";
import localFont from "next/font/local";
import { Providers } from "./providers";

const poppins = localFont({
  src: [
    { path: "../../assets/fonts/Poppins/Poppins-Thin.ttf", weight: "100" },
    {
      path: "../../assets/fonts/Poppins/Poppins-ExtraLight.ttf",
      weight: "200",
    },
    { path: "../../assets/fonts/Poppins/Poppins-Light.ttf", weight: "300" },
    { path: "../../assets/fonts/Poppins/Poppins-Regular.ttf", weight: "400" },
    { path: "../../assets/fonts/Poppins/Poppins-Medium.ttf", weight: "500" },
    { path: "../../assets/fonts/Poppins/Poppins-SemiBold.ttf", weight: "600" },
    { path: "../../assets/fonts/Poppins/Poppins-Bold.ttf", weight: "700" },
    { path: "../../assets/fonts/Poppins/Poppins-ExtraBold.ttf", weight: "800" },
    { path: "../../assets/fonts/Poppins/Poppins-Black.ttf", weight: "900" },
  ],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
